# Generated by Django 2.1.7 on 2019-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Додано'),
        ),
    ]
